apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    version: 0.0.3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      version: 0.0.5
  template:
    metadata:
      labels:
        app: nginx
        version: 0.0.5
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
