name: CI for Train

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: iris_train
  DIR: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          registry: ghcr.io
          path: .
          dockerfile: Dockerfile
          username: ${{ github.actor }}
          password: ${{ github.token }}
          push: true
          tags: |
            ghcr.io/ssuwani/iris_train:latest
            ghcr.io/ssuwani/iris_train:v1

      - name: Update Version
        run: echo update version