name: CI for Train

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: iris_train

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: docker version check
        run: docker --version

      - name: Docker Build
        run: echo docker build

      - name: Docker Push
        run: echo docker push

      - name: Update Version
        run: echo update version