name: CI for Train

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: iris_train
  DIR: .

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: "$REGISTRY/${{ github.actor }}/$IMAGE_NAME"
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -t $IMAGE $DIR
      - name: Docker Push
        run: |
          docker push $IMAGE

      - name: Update Version
        run: echo update version