name: CI for Train

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: iris_train
  IMAGE: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ GITHUB_SHA::6 }}
  DIR: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Docker Build
        run: |
          docker build -t ${{ env.IMAGE }} ${{ env.DIR }}

      - name: Docker Push
        run: |
          docker push ${{ env.IMAGE }}

      - name: Update Version
        run: echo update version