name: CI for Train

on: push

env:
  USERNAME: ssuwani
  REGISTRY: ghcr.io
  IMAGE_NAME: iris_train
  DIR: .


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.0
        with:
          path: .
          dockerfile: Dockerfile
          push: true
          tags: |
            $REGISTRY/$USERNAME/$IMAGE_NAME:latest
            $REGISTRY/$USERNAME/$IMAGE_NAME:${{ github.sha }}
#            ghcr.io/ssuwani/iris_train:latest
#            ghcr.io/ssuwani/iris_train:${{ github.sha }}

      - name: Update Version
        run: echo update version